language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer update
  - mysql -e 'create database selective_test;'

script: phpunit --configuration phpunit.xml --coverage-clover ./build/logs/clover.xml

after_script: php vendor/bin/coveralls -v