language: php

php:
  - 5.4
  - 5.5

env:
  - DB=sqlite

before_script: composer update

script: phpunit --configuration phpunit.xml --coverage-clover ./build/logs/clover.xml

after_script: php vendor/bin/coveralls -v